# Putting Purpose Into Practice

![](https://readwise-assets.s3.amazonaws.com/static/images/default-book-icon-0.c6917d331b03.png)

### Metadata

- Author: Colin Mayer and Bruno Roche
- Full Title: Putting Purpose Into Practice
- Category: #books

### Highlights

- This is the objective of what we call the Economics of Mutuality, which is about: 1. Putting purpose into practice through a new de finition of the boundaries of the business ecosystem of the firm, a more complete definition of performance, a more comprehensive process of value creation, and profit construction that go beyond financial profit alone; 2. Inspiring corporations with a tested means to access untapped resources to improve business performance in a holistic manner for people, planet, and profit; 3. Identifying how business and finance can restore their roles in society and the planet. ([Location 276](https://readwise.io/to_kindle?action=open&asin=None&location=276))
    - **Tags:** #blue
- It is only over the last sixty years since Milton Friedman first expounded his doctrine that ‘there is one and only one social purpose of business...to increase profits so long as it stays within the rules of the game’ that profits have emerged as the sole purpose of business. ([Location 336](https://readwise.io/to_kindle?action=open&asin=None&location=336))
    - **Tags:** #blue
- As Prosperity (Mayer 2018) argues, it is not profits per se that are the problem; it is the maximization of profit for the benefit of the shareholders at the expense of other stakeholders that is a mistake, as well as the presumption that profits are the ‘be all and end all’ of business and its sole purpose. Profits are not the sole purpose of business. The purpose of business is ‘to produce profitable solutions to the problems of people and planet, and not to profit from producing problems for people and planet’. In the process, business produces profits. But profits are not per se the purpose of business and business should not profit from producing problems for people and planet. ([Location 370](https://readwise.io/to_kindle?action=open&asin=None&location=370))
    - **Tags:** #blue
- Notions of reciprocal relations are not new in business and are not in themselves a particular innovation. ([Location 391](https://readwise.io/to_kindle?action=open&asin=None&location=391))
    - **Tags:** #blue
- what marks out the Economics of Mutuality from other similar ideas in relation to responsible business is its notion of what constitutes the firm, and also (most importantly, perhaps) its pragmatic approach to defining the effective boundaries of thefirm, to measuring nonfinancial performance with a set of simple, stable, and actionable metrics, and to leveraging the power of management and accounting to position mutuality at the core of thefirm. ([Location 392](https://readwise.io/to_kindle?action=open&asin=None&location=392))
    - **Tags:** #blue
- The problem, however, is not business ’ preoccupation with measurement. Rather, it is business’ obsession with the measurement of financial capital in the short term at the expense of nonfinancial forms of value without which the firm cannot operate effectively. ([Location 426](https://readwise.io/to_kindle?action=open&asin=None&location=426))
    - **Tags:** #blue
- The mutual P&L is a proposed change in the management account P&L, designed for internal use, that will modify the presentation of the financial P&L to take into account a business unit’s impact on selected human, social, and environmental capital issues. ([Location 437](https://readwise.io/to_kindle?action=open&asin=None&location=437))
    - **Tags:** #blue
- In particular, in so doing the research programme has brought out the importance of recognizing the two elements associated with purposeful business, namely not only ‘to produce profitable solutions to the problems of people and planet’ but also ‘not to profit from producing problems for people and planet’. The latter is important in avoiding the adverse consequences that doing well by doing good can create. That is to say, extending the boundaries of the firm beyond its property and contractual rights can be an intensified source of doing well by doing bad as well as good. Two examples will illustrate this. The ‘gig economy’ and the sharing instead of ownership of assets for the provision of taxi, delivery, property rental, and other services around the world provide forms of ‘employment’ with a greater degree of flexibility than previously existed. However, they also lack the security, protection, and insurance of traditional employment and risk exploiting vulnerable members of society with few or no alternatives available to them. Whether the gig economy is enabling or exploitative remains highly controversial. ([Location 512](https://readwise.io/to_kindle?action=open&asin=None&location=512))
    - **Tags:** #blue
- In both cases, companies may appear to be bene fiting—earning profits—by doing good—creating employment—where they are producing bad—insecurity and addiction. The profits are therefore illusory and do not satisfy the condition of avoiding producing one set of problems at the same time as they are solving others. ([Location 522](https://readwise.io/to_kindle?action=open&asin=None&location=522))
    - **Tags:** #blue
- the importance of extending the boundaries of the firm beyond property and contractual control rights to areas that traditionally would have been viewed as external to the firm. By internalizing such externalities, it encourages companies to address market failures themselves that previously have been the remit of governments. ([Location 548](https://readwise.io/to_kindle?action=open&asin=None&location=548))
    - **Tags:** #blue
- Some people might argue that it is the role of the board and senior management to ensure that there is a consistent set of purposes and values in an organization that reflect its fundamental objectives. However, what Mars illustrates is more of a ‘letting many flowers bloom’ approach that devolves decision-taking to individual units to determine the extent to which they believe it appropriate to adopt mutuality principles. In turn, over time, as experiments succeed and fail then a more consistent set of views as to what is appropriate for the company as a whole might emerge. ([Location 583](https://readwise.io/to_kindle?action=open&asin=None&location=583))
    - **Tags:** #blue
- In line with stakeholder theory, EoM places corporate purposes other than shareholder value at the heart of the firm and derives business practices on the basis of that. But it differs from stakeholder theories in emphasizing the importance of relations with stakeholders in delivering corporate purposes not the interests of stakeholders themselves. It also differs from existing models in looking at the boundaries of the firm beyond traditional ownership rights and contractual arrangements. It is therefore a problem-solving view of the firm as against a financially or stakeholder driven concept that embraces shareholders and stakeholders but does not put corporate purpose at the heart of either of them. ([Location 591](https://readwise.io/to_kindle?action=open&asin=None&location=591))
    - **Tags:** #blue
- It sets out an eight-step process around: (a) establishing a purpose, (b) designing metrics that measure the purpose, (c) identifying the relevant stakeholders, (d) mapping their objectives, capabilities, relationships, and pain points (i.e. problems), (e) selecting the pain points in the ecosystem that the organization should address, (f) measuring the baseline performance metrics before the intervention, (g) identifying, testing, and implementing the interventions to address the pain points, and (h) measuring the impact of the interventions on purpose and performance. ([Location 616](https://readwise.io/to_kindle?action=open&asin=None&location=616))
    - **Tags:** #blue
- The circular economy, in which manufacturers of products take responsibility for their disposal by recycling them back into the production process for their reuse in new products, is an example of mutually beneficial diminution of environmental and natural capital inputs across the value chain. ([Location 665](https://readwise.io/to_kindle?action=open&asin=None&location=665))
    - **Tags:** #blue
- As Chapter 14 states: ‘the mutual P&L is an extension of the financial P&L that takes into account selected human, social, and environmental issues that are relevant for the organization and its ecosystem toward a stated purpose.’ It describes four phases in the construction of a mutual P&L. The first is selection of relevant material issues; the second is the measurement of the creation and depletion of human, social, and natural capitals; the third is the valuation of impacts at cost as capital investments or depletion; the final stage is the integration and presentation of the mutual P&L in the company’s management accounting system. ([Location 731](https://readwise.io/to_kindle?action=open&asin=None&location=731))
    - **Tags:** #blue
